### ISSUE TITLE
Bug when trying to stop playback and startt playback with new request or URL

### ISSUE THREAD

**Issue by cyrmax** [gumerov-amir/TTMediaBot#3] opened 2021-05-25 18:19 UTC
Conditions:
* Windows 8.1 64 bit;
* Python 3.9.5;

Steps to reproduce:
* Select youtube service;
* Start playback from search or from URL;
* Stop playback (not pause);
* Immediately start another playback from search or from URL.

Expected behavior:
New playback starts as usualy.

Current behavior:
Bot throws the following error text in console and terminates:
`WARNING [2021-05-25 22:01:50,218]: Could not send HEAD request to http://stream.zeno.fm/p7sv1v10ss8uv: HTTP Error 400: Bad Request in MainThread file: YoutubeDL.py line 607 function report_warning`

Wishes:
Fix this please ASAP.

**Comment by a11cf0** [comment] 2021-05-25 19:07
I cannot reproduce this at all. Can you provide the exact requests/ URLs you used?

**Comment by DraganRatkovich** [comment] 2021-05-25 19:17
Hello,
The service was vk at default when issue happened, although I changed it to
YouTube, tryed to search for anything and issue appeared.
So, to give step-by-step details, things was follows:
I launched bot as usual, with all configs set correctly and bot entered
server successfully.
I pasted a link http://stream.zeno.fm/p7sv1v10ss8uv and pressed enter, bot
started playing normal, although after stoping playback and searching for
anything, pasting a link, no matter from which service, a previously sent
error appears.
Note. It does not matter, whether you paste a link or search for anything
at the first launch of bot, after second attempt, it crashes.

**Comment by cyrmax** [comment] 2021-05-25 21:11
@DraganRatkovich

Could you check the exact version of VLC which is installed in your system?
Also, if possible, provide, please, full path to VLC executable (vlc.exe) if i am right.

It seems like there are two possible issue reasons:
old VLC version which does not support some codec or inputs;
or some Windows 8.1 specific bug either in Python or in VLC.

Bug is not reproducible on Ubuntu 20.04, debian 10 docker container and Windows 10 64 bit, all works with the link given before.

**Comment by DraganRatkovich** [comment] 2021-05-26 06:12
@cyrmax  Hello,
Apologize for delay.
The vlc version is 3.0.14, downloaded from official website of vlc media player, and the full path is: "C:\Program Files\VideoLAN\VLC\vlc.exe"
Also, if needed, the Python installed on C:\Users\(Username)\AppData\Local\Programms\Python.

**Comment by DraganRatkovich** [comment] 2021-05-26 09:15
Hello,
I am zattaching a log file in Debug mode, so that developers can see it more accurately.
p.s. When playing any music from any service, without stopping previous song and directly sending another request, it sends and plays without problems, but when typing "s" to stop and play something other, the discribed problem appears.
[TTMediaBot.log](https://github.com/gumerov-amir/TTMediaBot/files/6545396/TTMediaBot.log)

**Comment by DraganRatkovich** [comment] 2021-05-26 15:37
@a11cf0  @gumerov-amir  @cyrmax  Hello,
When the above error appears after the second attempt to listen to something through the bot in Teamtalk, the following error also appears with the message: (Python stopped working, windows can check online solutions and close the program.) I clicked view details and the following lines were popped up:
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	python.exe
  Application Version:	3.9.5150.1013
  Application Timestamp:	60903347
  Fault Module Name:	WINMMBASE.dll
  Fault Module Version:	6.3.9600.17415
  Fault Module Timestamp:	54504013
  Exception Code:	c0000005
  Exception Offset:	000000000000cf38
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	1079
  Additional Information 1:	e149
  Additional Information 2:	e1490ca5e901cddfd15bf4f03780f119
  Additional Information 3:	e5b4
  Additional Information 4:	e5b47643b9cb345d559da4e74b4c9266

I don't know if this is a Windows bug or something in the bot's code, but I tried a lot of things before posting this comment here, for example. I uninstalled vlc player, virtual cable along with registry keys, tried to install previous versions of Python like 3.8, 3.7, etc. but still unsuccessfully.

**Comment by a11cf0** [comment] 2021-05-28 07:25
@DraganRatkovich This is a crash inside a Windows MME component caused by VLC. Currently I don't think we can do anything with it. This is most probably a Windows 8.1 specific bug/incompatibility with VLC. Try repeatedly starting and stopping playback from your stream's URL using VLC itself and report crashes if any.

**Comment by DraganRatkovich** [comment] 2021-05-28 18:49
@a11cf0  Hello,
I tried playing/stopping with vlc the stream several times, there were no errors, also I installed Windows 10 and everything works fine with no errors, so maybe this is a Windows 8.1 related bug

**Comment by a11cf0** [comment] 2021-05-28 21:15
@DraganRatkovich If you still have access to Windows 8.1 try setting the VLC's audio system to WaveOut and testing stream playback.

**Comment by DraganRatkovich** [comment] 2021-05-29 04:57
@a11cf0  Hello,
I tryed setting vlc audio output to waveaudio, vlc played everything without error, however, a same error appeared in Windows 8.1 when playback stopped in Teamtalk via the bot, so It's eyther Windows 8.1 or a Python related bug in 64 bit machines, because I read around the Web about this, in Windows 10 everything is clear.

**Comment by a11cf0** [comment] 2021-06-01 21:20
Closing this as specific to Windows 8.1/VLC interaction and practically unfixable at our end.

**Closed by a11cf0** 2021-06-01 21:20 UTC
