### ISSUE TITLE
Logging error and, maby mpv problem.

### ISSUE THREAD

**Issue by yukie-nobuharu** [gumerov-amir/TTMediaBot#31] opened 2021-08-26 04:11 UTC
Good day devs.
the following error has occurred. so, we can't get a log.
Note: we are using debian10.
and, we'll send more logs because, we also noticed, when it's been open for a long time, the application crashed.
here is the errors:
Exception inside python-mpv event loop:
Traceback (most recent call last):
  File "/opt/TTMediaBot/mpv.py", line 872, in _loop
    self._log_handler(ev['level'], ev['prefix'], ev['text'])
  File "/opt/TTMediaBot/bot/player/__init__.py", line 208, in log_handler
    logging.log(level, "{}: {}: {}".format(level, component, message))
  File "/usr/lib/python3.9/logging/__init__.py", line 2113, in log
    root.log(level, msg, *args, **kwargs)
  File "/usr/lib/python3.9/logging/__init__.py", line 1504, in log
    raise TypeError("level must be an integer")
TypeError: level must be an integer
Exception inside python-mpv event loop:
Traceback (most recent call last):
  File "/opt/TTMediaBot/mpv.py", line 872, in _loop
    self._log_handler(ev['level'], ev['prefix'], ev['text'])
  File "/opt/TTMediaBot/bot/player/__init__.py", line 208, in log_handler
    logging.log(level, "{}: {}: {}".format(level, component, message))
  File "/usr/lib/python3.9/logging/__init__.py", line 2113, in log
    root.log(level, msg, *args, **kwargs)
  File "/usr/lib/python3.9/logging/__init__.py", line 1504, in log
    raise TypeError("level must be an integer")
TypeError: level must be an integer

**Comment by yukie-nobuharu** [comment] 2021-08-29 01:35
Hi devs. I think the Issue is, the application uses a lot of system memory in the long run. so it is killed by debian memory management. but, we still have a problem with logs. We still can't get logs because of the error.

**Comment by yukie-nobuharu** [comment] 2021-08-29 07:15
Ok, we dont know how it happeneds but, the bot is not responding to commands.
here is the errors.
Exception in thread TeamTalkThread:
ValueError: 1024 is not a valid UserStatusMode

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/opt/TTMediaBot/bot/TeamTalk/thread.py", line 43, in run
    self.ttclient.message_queue.put(self.ttclient.get_message(msg.textmessage))
  File "/opt/TTMediaBot/bot/TeamTalk/__init__.py", line 296, in get_message
    return Message(re.sub(re_line_endings, '', _str(msg.szMessage)), self.get_user(msg.nFromUserID), self.get_channel(msg.nChannelID), MessageType(msg.nMsgType))
  File "/opt/TTMediaBot/bot/TeamTalk/__init__.py", line 313, in get_user
    gender = UserStatusMode(user.nStatusMode)
  File "/usr/lib/python3.9/enum.py", line 360, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.9/enum.py", line 684, in __new__
    raise exc
  File "/usr/lib/python3.9/enum.py", line 668, in __new__
    result = cls._missing_(value)
  File "/usr/lib/python3.9/enum.py", line 808, in _missing_
    possible_member = cls._create_pseudo_member_(value)
  File "/usr/lib/python3.9/enum.py", line 823, in _create_pseudo_member_
    raise ValueError("%r is not a valid %s" % (value, cls.__qualname__))
ValueError: 1024 is not a valid UserStatusMode

**Comment by rexya2017** [comment] 2021-09-17 12:01
I think the error was caused by someone changing the status to question mode, or status while streaming a mediafile, and send commands to bots.
Here's the error I get from the terminal screen:
Exception in thread TeamTalkThread:
ValueError: 6144 is not a valid UserStatusMode

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rexya\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "D:\AudioPlayer\thetest\bot\TeamTalk\thread.py", line 43, in run
    self.ttclient.message_queue.put(self.ttclient.get_message(msg.textmessage))
  File "D:\AudioPlayer\thetest\bot\TeamTalk\__init__.py", line 296, in get_message
    return Message(re.sub(re_line_endings, '', _str(msg.szMessage)), self.get_user(msg.nFromUserID), self.get_channel(msg.nChannelID), MessageType(msg.nMsgType))
  File "D:\AudioPlayer\thetest\bot\TeamTalk\__init__.py", line 313, in get_user
    gender = UserStatusMode(user.nStatusMode)
  File "C:\Users\rexya\AppData\Local\Programs\Python\Python39\lib\enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "C:\Users\rexya\AppData\Local\Programs\Python\Python39\lib\enum.py", line 709, in __new__
    raise exc
  File "C:\Users\rexya\AppData\Local\Programs\Python\Python39\lib\enum.py", line 692, in __new__
    result = cls._missing_(value)
  File "C:\Users\rexya\AppData\Local\Programs\Python\Python39\lib\enum.py", line 837, in _missing_
    possible_member = cls._create_pseudo_member_(value)
  File "C:\Users\rexya\AppData\Local\Programs\Python\Python39\lib\enum.py", line 852, in _create_pseudo_member_
    raise ValueError("%r is not a valid %s" % (value, cls.__qualname__))
ValueError: 6144 is not a valid UserStatusMode

I get this error when I Stream a mediafile, and send the s command to bot.

**Comment by yukie-nobuharu** [comment] 2021-09-17 14:21
o, I think, you are right.

**Comment by a11cf0** [comment] 2021-09-17 16:21
Thanks. This should be fixed now. Please test the latest commit and report the results.

**Comment by rexya2017** [comment] 2021-09-17 16:50
> Thanks. This should be fixed now. Please test the latest commit and report the results.

fix now, thanks alot. :)

**Closed** 2021-09-17 17:08 UTC
